name: NASA Project Example CI
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build: 
    env:
      CI: true
      MONGO_URL_TEST: mongodb://localhost/nasa-test
      # PORT: 5000
    strategy:
      matrix:
        node-version: ['16.x', '20.x']
        mongodb-version: ['7.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js vesrion ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Start MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: nasa-test
      - run: npm ci
      - run: npm run build --prefix ./client
      - run: npm run test
  #deploy:
    #needs: build